
version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
      - "11432:11432"
    environment:
      - OLLAMA_URL=http://localhost:11432
    networks:
      - default

networks:
  default:
    driver: bridge
